//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace Marketplace.com.umbraco.orders {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OrdersSoap", Namespace="http://tempuri.org/")]
    public partial class Orders : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFromEcommerceIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFromTransactionIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback LinkProfilesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Orders() {
            this.Url = global::Marketplace.Properties.Settings.Default.Marketplace_com_umbraco_orders_Orders;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event GetFromEcommerceIDCompletedEventHandler GetFromEcommerceIDCompleted;
        
        /// <remarks/>
        public event GetFromTransactionIDCompletedEventHandler GetFromTransactionIDCompleted;
        
        /// <remarks/>
        public event LinkProfilesCompletedEventHandler LinkProfilesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Create", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderProxy Create(OrderProxy order, bool testMode, string login, string password) {
            object[] results = this.Invoke("Create", new object[] {
                        order,
                        testMode,
                        login,
                        password});
            return ((OrderProxy)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(OrderProxy order, bool testMode, string login, string password) {
            this.CreateAsync(order, testMode, login, password, null);
        }
        
        /// <remarks/>
        public void CreateAsync(OrderProxy order, bool testMode, string login, string password, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        order,
                        testMode,
                        login,
                        password}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFromEcommerceID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderProxy GetFromEcommerceID(int EcommerceOrderID, string login, string password) {
            object[] results = this.Invoke("GetFromEcommerceID", new object[] {
                        EcommerceOrderID,
                        login,
                        password});
            return ((OrderProxy)(results[0]));
        }
        
        /// <remarks/>
        public void GetFromEcommerceIDAsync(int EcommerceOrderID, string login, string password) {
            this.GetFromEcommerceIDAsync(EcommerceOrderID, login, password, null);
        }
        
        /// <remarks/>
        public void GetFromEcommerceIDAsync(int EcommerceOrderID, string login, string password, object userState) {
            if ((this.GetFromEcommerceIDOperationCompleted == null)) {
                this.GetFromEcommerceIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFromEcommerceIDOperationCompleted);
            }
            this.InvokeAsync("GetFromEcommerceID", new object[] {
                        EcommerceOrderID,
                        login,
                        password}, this.GetFromEcommerceIDOperationCompleted, userState);
        }
        
        private void OnGetFromEcommerceIDOperationCompleted(object arg) {
            if ((this.GetFromEcommerceIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFromEcommerceIDCompleted(this, new GetFromEcommerceIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFromTransactionID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderProxy GetFromTransactionID(string transaction, string login, string password) {
            object[] results = this.Invoke("GetFromTransactionID", new object[] {
                        transaction,
                        login,
                        password});
            return ((OrderProxy)(results[0]));
        }
        
        /// <remarks/>
        public void GetFromTransactionIDAsync(string transaction, string login, string password) {
            this.GetFromTransactionIDAsync(transaction, login, password, null);
        }
        
        /// <remarks/>
        public void GetFromTransactionIDAsync(string transaction, string login, string password, object userState) {
            if ((this.GetFromTransactionIDOperationCompleted == null)) {
                this.GetFromTransactionIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFromTransactionIDOperationCompleted);
            }
            this.InvokeAsync("GetFromTransactionID", new object[] {
                        transaction,
                        login,
                        password}, this.GetFromTransactionIDOperationCompleted, userState);
        }
        
        private void OnGetFromTransactionIDOperationCompleted(object arg) {
            if ((this.GetFromTransactionIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFromTransactionIDCompleted(this, new GetFromTransactionIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LinkProfiles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BuyerProxy LinkProfiles(string profileEmail, string profilePassword, string login, string password) {
            object[] results = this.Invoke("LinkProfiles", new object[] {
                        profileEmail,
                        profilePassword,
                        login,
                        password});
            return ((BuyerProxy)(results[0]));
        }
        
        /// <remarks/>
        public void LinkProfilesAsync(string profileEmail, string profilePassword, string login, string password) {
            this.LinkProfilesAsync(profileEmail, profilePassword, login, password, null);
        }
        
        /// <remarks/>
        public void LinkProfilesAsync(string profileEmail, string profilePassword, string login, string password, object userState) {
            if ((this.LinkProfilesOperationCompleted == null)) {
                this.LinkProfilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLinkProfilesOperationCompleted);
            }
            this.InvokeAsync("LinkProfiles", new object[] {
                        profileEmail,
                        profilePassword,
                        login,
                        password}, this.LinkProfilesOperationCompleted, userState);
        }
        
        private void OnLinkProfilesOperationCompleted(object arg) {
            if ((this.LinkProfilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LinkProfilesCompleted(this, new LinkProfilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderProxy {
        
        private OrderLineProxy[] orderLinesField;
        
        private System.DateTime createdField;
        
        private BuyerProxy buyerField;
        
        private OrderStatus orderStatusField;
        
        private string invoicePathField;
        
        private int deliOrderIDField;
        
        private int ecommerceOrderIDField;
        
        private string purchaseOrderField;
        
        private string transactionIDField;
        
        /// <remarks/>
        public OrderLineProxy[] OrderLines {
            get {
                return this.orderLinesField;
            }
            set {
                this.orderLinesField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public BuyerProxy Buyer {
            get {
                return this.buyerField;
            }
            set {
                this.buyerField = value;
            }
        }
        
        /// <remarks/>
        public OrderStatus OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
            }
        }
        
        /// <remarks/>
        public string InvoicePath {
            get {
                return this.invoicePathField;
            }
            set {
                this.invoicePathField = value;
            }
        }
        
        /// <remarks/>
        public int DeliOrderID {
            get {
                return this.deliOrderIDField;
            }
            set {
                this.deliOrderIDField = value;
            }
        }
        
        /// <remarks/>
        public int EcommerceOrderID {
            get {
                return this.ecommerceOrderIDField;
            }
            set {
                this.ecommerceOrderIDField = value;
            }
        }
        
        /// <remarks/>
        public string PurchaseOrder {
            get {
                return this.purchaseOrderField;
            }
            set {
                this.purchaseOrderField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderLineProxy {
        
        private decimal amountField;
        
        private string descriptionField;
        
        private int quantityField;
        
        private System.Guid productIDField;
        
        private int vendorEconomicIDField;
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        public int VendorEconomicID {
            get {
                return this.vendorEconomicIDField;
            }
            set {
                this.vendorEconomicIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BuyerProxy {
        
        private string nameField;
        
        private string emailField;
        
        private string loginField;
        
        private string companyField;
        
        private string vATField;
        
        private bool vatInvalidField;
        
        private string addressField;
        
        private string countryField;
        
        private string phoneField;
        
        private string ipField;
        
        private int umbracoComMemberIDField;
        
        private System.Guid umbracoComMemberGuidField;
        
        private int ourMemberIdField;
        
        private System.Guid ourMemberGuidField;
        
        private string[] groupsField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string VAT {
            get {
                return this.vATField;
            }
            set {
                this.vATField = value;
            }
        }
        
        /// <remarks/>
        public bool VatInvalid {
            get {
                return this.vatInvalidField;
            }
            set {
                this.vatInvalidField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string IP {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        public int umbracoComMemberID {
            get {
                return this.umbracoComMemberIDField;
            }
            set {
                this.umbracoComMemberIDField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid umbracoComMemberGuid {
            get {
                return this.umbracoComMemberGuidField;
            }
            set {
                this.umbracoComMemberGuidField = value;
            }
        }
        
        /// <remarks/>
        public int ourMemberId {
            get {
                return this.ourMemberIdField;
            }
            set {
                this.ourMemberIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ourMemberGuid {
            get {
                return this.ourMemberGuidField;
            }
            set {
                this.ourMemberGuidField = value;
            }
        }
        
        /// <remarks/>
        public string[] Groups {
            get {
                return this.groupsField;
            }
            set {
                this.groupsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum OrderStatus {
        
        /// <remarks/>
        Accepted,
        
        /// <remarks/>
        Refused,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderProxy Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderProxy)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetFromEcommerceIDCompletedEventHandler(object sender, GetFromEcommerceIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFromEcommerceIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFromEcommerceIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderProxy Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderProxy)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetFromTransactionIDCompletedEventHandler(object sender, GetFromTransactionIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFromTransactionIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFromTransactionIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderProxy Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderProxy)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void LinkProfilesCompletedEventHandler(object sender, LinkProfilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkProfilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LinkProfilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BuyerProxy Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BuyerProxy)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591