//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jering.Markdig.Extensions.FlexiBlocks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jering.Markdig.Extensions.FlexiBlocks.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple attempts to retrieve content from the remote URI &quot;{0}&quot; have failed. Please ensure that the URI is valid and that your network connection is stable. Enable debug level logging and try again for more information on why requests are failing..
        /// </summary>
        internal static string ArgumentException_ContentRetrieverService_FailedAfterMultipleAttempts {
            get {
                return ResourceManager.GetString("ArgumentException_ContentRetrieverService_FailedAfterMultipleAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the remote URI &quot;{0}&quot; is forbidden..
        /// </summary>
        internal static string ArgumentException_ContentRetrieverService_RemoteUriAccessForbidden {
            get {
                return ResourceManager.GetString("ArgumentException_ContentRetrieverService_RemoteUriAccessForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote URI &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string ArgumentException_ContentRetrieverService_RemoteUriDoesNotExist {
            get {
                return ResourceManager.GetString("ArgumentException_ContentRetrieverService_RemoteUriDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URI &quot;{0}&quot; has unsupported scheme &quot;{1}&quot;..
        /// </summary>
        internal static string ArgumentException_ContentRetrieverService_UnsupportedScheme {
            get {
                return ResourceManager.GetString("ArgumentException_ContentRetrieverService_UnsupportedScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local URI &quot;{0}&quot; is invalid. Refer to the inner exception for more details..
        /// </summary>
        internal static string ArgumentException_Shared_InvalidLocalUri {
            get {
                return ResourceManager.GetString("ArgumentException_Shared_InvalidLocalUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection..
        /// </summary>
        internal static string ArgumentException_Shared_InvalidOffLen {
            get {
                return ResourceManager.GetString("ArgumentException_Shared_InvalidOffLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null, whitespace or an empty string..
        /// </summary>
        internal static string ArgumentException_Shared_ValueCannotBeNullWhitespaceOrAnEmptyString {
            get {
                return ResourceManager.GetString("ArgumentException_Shared_ValueCannotBeNullWhitespaceOrAnEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &quot;{0}&quot; must be of type &quot;{1}&quot;. A value of type &quot;{2}&quot; was specified..
        /// </summary>
        internal static string ArgumentException_Shared_ValueMustBeOfExpectedType {
            get {
                return ResourceManager.GetString("ArgumentException_Shared_ValueMustBeOfExpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer cannot be null..
        /// </summary>
        internal static string ArgumentNullException_Shared_Buffer {
            get {
                return ResourceManager.GetString("ArgumentNullException_Shared_Buffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be negative. The specified value &quot;{0}&quot; is invalid..
        /// </summary>
        internal static string ArgumentOutOfRangeException_Shared_ValueCannotBeNegative {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_Shared_ValueCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is invalid because it is not greater than the &quot;{1}&quot; value &quot;{2}&quot;..
        /// </summary>
        internal static string ArgumentOutOfRangeException_Shared_ValueMustBeGreaterThanOtherValue {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_Shared_ValueMustBeGreaterThanOtherValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be within range {0}. The specified value &quot;{1}&quot; is invalid..
        /// </summary>
        internal static string ArgumentOutOfRangeException_Shared_ValueMustBeWithinRange {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_Shared_ValueMustBeWithinRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is invalid because it is less than the &quot;{1}&quot; value &quot;{2}&quot;..
        /// </summary>
        internal static string ArgumentOutOfRangeException_Shared_ValueMustNotBeLessThanOtherValue {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_Shared_ValueMustNotBeLessThanOtherValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while processing the block. Refer to the inner exception for more details..
        /// </summary>
        internal static string BlockException_BlockException_ExceptionOccurredWhileProcessingBlock {
            get {
                return ResourceManager.GetString("BlockException_BlockException_ExceptionOccurredWhileProcessingBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} at line &quot;{1}&quot;, column &quot;{2}&quot;, is invalid:
        ///{3}.
        /// </summary>
        internal static string BlockException_BlockException_InvalidBlock {
            get {
                return ResourceManager.GetString("BlockException_BlockException_InvalidBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred in &quot;{0}&quot; while attempting to open a block. Refer to the inner exception for more details..
        /// </summary>
        internal static string BlockException_BlockParser_ExceptionOccurredWhileAttemptingToOpenBlock {
            get {
                return ResourceManager.GetString("BlockException_BlockParser_ExceptionOccurredWhileAttemptingToOpenBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while processing content from the FlexiIncludeBlock&apos;s source, &quot;{0}&quot;. Refer to the inner exception for more details..
        /// </summary>
        internal static string BlockException_FlexiIncludeBlockFactory_ExceptionOccurredWhileProcessingContent {
            get {
                return ResourceManager.GetString("BlockException_FlexiIncludeBlockFactory_ExceptionOccurredWhileProcessingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexiOptionsBlock must be consumed..
        /// </summary>
        internal static string BlockException_FlexiOptionsBlockParser_UnconsumedBlock {
            get {
                return ResourceManager.GetString("BlockException_FlexiOptionsBlockParser_UnconsumedBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must have &quot;{1}&quot; part(s), found &quot;{2}&quot; part(s)..
        /// </summary>
        internal static string BlockException_MultipartBlockParser_IncorrectNumberOfParts {
            get {
                return ResourceManager.GetString("BlockException_MultipartBlockParser_IncorrectNumberOfParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must exist within a {1}..
        /// </summary>
        internal static string BlockException_Shared_BlockCanOnlyExistWithinASpecificTypeOfBlock {
            get {
                return ResourceManager.GetString("BlockException_Shared_BlockCanOnlyExistWithinASpecificTypeOfBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must only contain {1}s. A {2} was found. .
        /// </summary>
        internal static string BlockException_Shared_BlockMustOnlyContainASpecificTypeOfBlock {
            get {
                return ResourceManager.GetString("BlockException_Shared_BlockMustOnlyContainASpecificTypeOfBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while creating the block. Refer to the inner exception for more details..
        /// </summary>
        internal static string BlockException_Shared_ExceptionOccurredWhileCreatingBlock {
            get {
                return ResourceManager.GetString("BlockException_Shared_ExceptionOccurredWhileCreatingBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The disk cache directory &quot;{0}&quot; is invalid. Refer to the inner exception for more details..
        /// </summary>
        internal static string InvalidOperationException_DiskCacheService_InvalidDiskCacheDirectory {
            get {
                return ResourceManager.GetString("InvalidOperationException_DiskCacheService_InvalidDiskCacheDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected exception occurred when attempting to retrieve the source for &quot;{0}&quot;, from the disk cache at &quot;{1}&quot;. Refer to the inner exception for more information..
        /// </summary>
        internal static string InvalidOperationException_DiskCacheService_UnexpectedDiskCacheException {
            get {
                return ResourceManager.GetString("InvalidOperationException_DiskCacheService_UnexpectedDiskCacheException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following FlexiIncludeBlocks cycle was found: 
        ///{0}.
        /// </summary>
        internal static string InvalidOperationException_FlexiIncludeBlockFactory_CycleFound {
            get {
                return ResourceManager.GetString("InvalidOperationException_FlexiIncludeBlockFactory_CycleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read dimensions from local image file &quot;{0}&quot;. The file is either corrupted or encoded in an unsupported format..
        /// </summary>
        internal static string InvalidOperationException_ImageService_UnableToReadDimensionsFromImageFile {
            get {
                return ResourceManager.GetString("InvalidOperationException_ImageService_UnableToReadDimensionsFromImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attempt to run &quot;{0}&quot; with arguments &quot;{1}&quot; and timeout &quot;{2}&quot; failed.
        ///
        ///Standard output: {3}
        ///
        ///Refer to the inner exception for more details..
        /// </summary>
        internal static string InvalidOperationException_ProcessService_ExceptionThrownWhileAttemptingToRunExecutable {
            get {
                return ResourceManager.GetString("InvalidOperationException_ProcessService_ExceptionThrownWhileAttemptingToRunExecu" +
                        "table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attempt to run &quot;{0}&quot; with arguments &quot;{1}&quot; failed with exit code &quot;{2}&quot;.
        ///
        ///Standard output: {3}
        ///
        ///Error output: {4}.
        /// </summary>
        internal static string InvalidOperationException_ProcessService_ExecutableRunFailed {
            get {
                return ResourceManager.GetString("InvalidOperationException_ProcessService_ExecutableRunFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg is required for file operations like retrieving a video&apos;s duration and dimensions or generating a poster:
        ///
        ///1. Download FFmpeg from https://ffmpeg.org.
        ///2. Add the executable&apos;s directory to the path environment variable.
        ///
        ///Alternatively, disable file operations by setting &quot;EnableFileOperations&quot; to false for all FlexiVideoBlocks..
        /// </summary>
        internal static string InvalidOperationException_VideoService_FfmpegRequired {
            get {
                return ResourceManager.GetString("InvalidOperationException_VideoService_FfmpegRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video &quot;{0}&quot; has invalid metadata. The following was returned when trying to retrieve its width, height and duration: 
        ///{1}.
        /// </summary>
        internal static string InvalidOperationException_VideoService_InvalidVideoMetadata {
            get {
                return ResourceManager.GetString("InvalidOperationException_VideoService_InvalidVideoMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read dimensions from the local image file &quot;{0}&quot;. Refer to the inner exception for more details..
        /// </summary>
        internal static string InvalidOperationsException_ImageService_ExceptionThrownWhileAttemptingToReadDimensionsFromLocalImageFile {
            get {
                return ResourceManager.GetString("InvalidOperationsException_ImageService_ExceptionThrownWhileAttemptingToReadDimen" +
                        "sionsFromLocalImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON &quot;{0}&quot;..
        /// </summary>
        internal static string JsonException_Shared_InvalidJson {
            get {
                return ResourceManager.GetString("JsonException_Shared_InvalidJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http request to &quot;{0}&quot; failed with status code &quot;{1}&quot;, {2} tries remaining..
        /// </summary>
        internal static string LogWarning_ContentRetrieverService_FailureStatusCode {
            get {
                return ResourceManager.GetString("LogWarning_ContentRetrieverService_FailureStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A HttpRequestException with message &quot;{0}&quot; occurred when attempting to retrieve content from &quot;{1}&quot;, {2} tries remaining..
        /// </summary>
        internal static string LogWarning_ContentRetrieverService_HttpRequestException {
            get {
                return ResourceManager.GetString("LogWarning_ContentRetrieverService_HttpRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to retrieve content from &quot;{0}&quot; timed out, {1} tries remaining..
        /// </summary>
        internal static string LogWarning_ContentRetrieverService_Timeout {
            get {
                return ResourceManager.GetString("LogWarning_ContentRetrieverService_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; is in use. {1} tries remaining..
        /// </summary>
        internal static string LogWarning_DiskCacheService_FileInUse {
            get {
                return ResourceManager.GetString("LogWarning_DiskCacheService_FileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read from a closed TextReader..
        /// </summary>
        internal static string ObjectDisposedException_Shared_ReaderClosed {
            get {
                return ResourceManager.GetString("ObjectDisposedException_Shared_ReaderClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON &quot;{0}&quot;. Refer to the inner exception for more details..
        /// </summary>
        internal static string OptionsException_BlockOptionsFactory_InvalidJson {
            get {
                return ResourceManager.GetString("OptionsException_BlockOptionsFactory_InvalidJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The line number ranges &quot;{0}&quot; and &quot;{1}&quot; overlap..
        /// </summary>
        internal static string OptionsException_FlexiCodeBlocks_OverlappingLineNumbers {
            get {
                return ResourceManager.GetString("OptionsException_FlexiCodeBlocks_OverlappingLineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No line after the start line contains the string &quot;{0}&quot;..
        /// </summary>
        internal static string OptionsException_FlexiIncludeBlockFactory_NoLineContainsEndString {
            get {
                return ResourceManager.GetString("OptionsException_FlexiIncludeBlockFactory_NoLineContainsEndString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No line contains the string &quot;{0}&quot;..
        /// </summary>
        internal static string OptionsException_FlexiIncludeBlockFactory_NoLineContainsStartString {
            get {
                return ResourceManager.GetString("OptionsException_FlexiIncludeBlockFactory_NoLineContainsStartString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to normalize &quot;{0}&quot; for {1} links..
        /// </summary>
        internal static string OptionsException_FlexiQuoteBlockFactory_UnableToNormalize {
            get {
                return ResourceManager.GetString("OptionsException_FlexiQuoteBlockFactory_UnableToNormalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is invalid for tables with cells that have rowspan or colspan..
        /// </summary>
        internal static string OptionsException_FlexiTableBlockFactory_TypeInvalidForTablesWithCellsThatHaveRowspanOrColspan {
            get {
                return ResourceManager.GetString("OptionsException_FlexiTableBlockFactory_TypeInvalidForTablesWithCellsThatHaveRows" +
                        "panOrColspan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is invalid for tables with multiple header rows..
        /// </summary>
        internal static string OptionsException_FlexiTableBlockFactory_TypeInvalidForTablesWithMultipleHeaderRows {
            get {
                return ResourceManager.GetString("OptionsException_FlexiTableBlockFactory_TypeInvalidForTablesWithMultipleHeaderRow" +
                        "s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The options &quot;Start&quot; and &quot;End&quot; are invalid: The end line cannot occur before the start line. The combination of start &quot;{0}&quot; and end &quot;{1}&quot; is invalid. .
        /// </summary>
        internal static string OptionsException_LineRange_EndLineBeStartLineOrALineAfterIt {
            get {
                return ResourceManager.GetString("OptionsException_LineRange_EndLineBeStartLineOrALineAfterIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The options &quot;Start&quot; and &quot;End&quot; are invalid: Unable to normalize &quot;{0}&quot; for {1} lines. After normalization, start is &quot;{2}&quot; and end is &quot;{3}&quot;, which is invalid. .
        /// </summary>
        internal static string OptionsException_LineRange_UnableToNormalize {
            get {
                return ResourceManager.GetString("OptionsException_LineRange_UnableToNormalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for option &quot;{0}&quot;: &quot;{1}&quot;.
        /// </summary>
        internal static string OptionsException_OptionsException_InvalidOption {
            get {
                return ResourceManager.GetString("OptionsException_OptionsException_InvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Included&quot; array for phrase group &quot;{0}&quot; is invalid. Only {1} matches were found for the regex expression, the included index &quot;{2}&quot; is out of range..
        /// </summary>
        internal static string OptionsException_PhraseGroup_IncludedMatchIndexOutOfRange {
            get {
                return ResourceManager.GetString("OptionsException_PhraseGroup_IncludedMatchIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string OptionsException_Shared_DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("OptionsException_Shared_DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; was not found in directory &quot;{1}&quot;..
        /// </summary>
        internal static string OptionsException_Shared_FileNotFoundInDirectory {
            get {
                return ResourceManager.GetString("OptionsException_Shared_FileNotFoundInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is invalid..
        /// </summary>
        internal static string OptionsException_Shared_InvalidValue {
            get {
                return ResourceManager.GetString("OptionsException_Shared_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected 1 file, but &quot;{0}&quot; files with name &quot;{1}&quot; were found in directory &quot;{2}&quot;:
        ///{3}.
        /// </summary>
        internal static string OptionsException_Shared_MultipleFilesFoundInDirectory {
            get {
                return ResourceManager.GetString("OptionsException_Shared_MultipleFilesFoundInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve files from directory &quot;{0}&quot;. Refer to the inner exception for more details..
        /// </summary>
        internal static string OptionsException_Shared_UnableToRetrieveFilesFromDirectory {
            get {
                return ResourceManager.GetString("OptionsException_Shared_UnableToRetrieveFilesFromDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URI &quot;{0}&quot; contains invalid characters..
        /// </summary>
        internal static string OptionsException_Shared_UriContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("OptionsException_Shared_UriContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is invalid, expected an absolute URI..
        /// </summary>
        internal static string OptionsException_Shared_ValueMustBeAnAbsoluteUri {
            get {
                return ResourceManager.GetString("OptionsException_Shared_ValueMustBeAnAbsoluteUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; with scheme &quot;{1}&quot; is invalid. Expected a URI with scheme {2}..
        /// </summary>
        internal static string OptionsException_Shared_ValueMustBeAUriWithASupportedScheme {
            get {
                return ResourceManager.GetString("OptionsException_Shared_ValueMustBeAUriWithASupportedScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is not within the range of valid values for the enum {1}..
        /// </summary>
        internal static string OptionsException_Shared_ValueMustBeAValidEnumValue {
            get {
                return ResourceManager.GetString("OptionsException_Shared_ValueMustBeAValidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is invalid, expected a valid URI..
        /// </summary>
        internal static string OptionsException_Shared_ValueMustBeAValidUri {
            get {
                return ResourceManager.GetString("OptionsException_Shared_ValueMustBeAValidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is invalid, expected an integer greater than 0..
        /// </summary>
        internal static string OptionsException_Shared_ValueMustBeIntegerGreaterThan0 {
            get {
                return ResourceManager.GetString("OptionsException_Shared_ValueMustBeIntegerGreaterThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is invalid, expected a number within the range {1}..
        /// </summary>
        internal static string OptionsException_Shared_ValueMustBeWithinRange {
            get {
                return ResourceManager.GetString("OptionsException_Shared_ValueMustBeWithinRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is invalid, expected a non-negative integer..
        /// </summary>
        internal static string OptionsException_Shared_ValueMustNotBeNegative {
            get {
                return ResourceManager.GetString("OptionsException_Shared_ValueMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be null..
        /// </summary>
        internal static string OptionsException_Shared_ValueMustNotBeNull {
            get {
                return ResourceManager.GetString("OptionsException_Shared_ValueMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be null, whitespace or an empty string..
        /// </summary>
        internal static string OptionsException_Shared_ValueMustNotBeNullWhitespaceOrAnEmptyString {
            get {
                return ResourceManager.GetString("OptionsException_Shared_ValueMustNotBeNullWhitespaceOrAnEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is invalid, expected a URI that points to a file..
        /// </summary>
        internal static string OptionsException_Shared_ValueMustPointToAFile {
            get {
                return ResourceManager.GetString("OptionsException_Shared_ValueMustPointToAFile", resourceCulture);
            }
        }
    }
}
